### PR TITLE
Flutter migration v2

### PR DESCRIPTION
**Pull request by squallsama**

### CODE REVIEW

**Comment by yutae** [comment]
@ko2ic 

Please review this PR.

**Comment by MrAlek** [comment]
@ko2ic any updates on this?

**Comment by ko2ic** [comment]
@squallsama 

Thank you for your contribution!
Sorry for the delay. @yutae @MrAlek 
I'll check it out and merge it.

**Comment by MrAlek** [comment]
Thank you @ko2ic. Much appreciated! 👏 🙏

**Pull request merged**
